Imports GTA.Native

Namespace INM

    Module INMNative

        Public BEGIN_HIDE_MAP_OBJECT_THIS_FRAME As Hash = Hash._0x4B5CFC83122DF602
        Public DISABLE_OCCLUSION_THIS_FRAME As Hash = Hash._0x3669F1B198DCAA4F
        Public PIN_INTERIOR_IN_MEMORY As Hash = Hash._0x2CA429C029CCF247
        Public _GET_VEHICLE_ROOF_LIVERY As Hash = &H60190048C0764A26UL
        Public _SET_VEHICLE_ROOF_LIVERY As Hash = &HA6D3A8750DC73270UL
        Public _GET_VEHICLE_XENON_LIGHTS_COLOR As Hash = &H3DFF319A831E0CDB
        Public _SET_VEHICLE_XENON_LIGHTS_COLOR As Hash = &HE41033B25D003A07UL
        Public _GET_MAKE_NAME_FROM_VEHICLE_MODEL As Hash = &HF7AF4F159FF99F97UL
        Public COPY_VEHICLE_DAMAGES As Hash = Hash._0xE44A982368A4AF23
        Public _SET_SPECIALFLIGHT_WING_RATIO As Hash = &H70A252F60A3E036B
        Public GET_SCREEN_COORD_FROM_WORLD_COORD As Hash = Hash._WORLD3D_TO_SCREEN2D
        Public GET_CONTROL_INSTRUCTIONAL_BUTTON As Hash = Hash._0x0499D7B09FC9B407
        Public ON_ENTER_MP As Hash = Hash._LOAD_MP_DLC_MAPS
        Public ACTIVATE_INTERIOR_ENTITY_SET As Hash = Hash._ENABLE_INTERIOR_PROP
        Public GET_VEHICLE_ESTIMATED_MAX_SPEED As Hash = Hash._GET_VEHICLE_MAX_SPEED
        Public ANIMPOSTFX_PLAY As Hash = Hash._START_SCREEN_EFFECT
        Public ANIMPOSTFX_STOP As Hash = Hash._STOP_SCREEN_EFFECT

    End Module

End Namespace